DROP PACKAGE PC_JUGADOR;
DROP PACKAGE PC_EQUIPO;
DROP PACKAGE PC_PATROCINADOR;
DROP PACKAGE PC_EVALUACION;
DROP PACKAGE PC_MENTAL;
DROP PACKAGE PC_FISICO;
DROP PACKAGE PC_EVENTOS;
DROP PACKAGE PC_PARTIDO;