---Seguridad---

-- Crear roles para Presidente, Medico y Arbitro
CREATE ROLE C##PRESIDENTE;
CREATE ROLE C##MEDICO;
CREATE ROLE C##ARBITRO;

-- Asignar permisos a roles para tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON Jugador TO C##PRESIDENTE;
GRANT SELECT, INSERT, UPDATE ON Evaluacion TO C##MEDICO;
GRANT SELECT, INSERT, UPDATE ON Eventos_Partido TO C##ARBITRO;

-- Asignar permisos a roles para procedimientos
GRANT EXECUTE ON PC_PRESIDENTE TO C##PRESIDENTE;
GRANT EXECUTE ON PC_MEDICO TO C##MEDICO;
GRANT EXECUTE ON PC_ARBITRO TO C##ARBITRO;

-- Asignar USUARIOS
    
CREATE USER C##PROFESOR
IDENTIFIED BY P1234
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;

CREATE USER C##MARCO
IDENTIFIED BY M1234
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;

CREATE USER C##ANDRES
IDENTIFIED BY A1234
DEFAULT TABLESPACE SYSTEM
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON SYSTEM;

GRANT CREATE SESSION TO C##PROFESOR;
GRANT CREATE SESSION TO C##MARCO;
GRANT CREATE SESSION TO C##ANDRES;

GRANT CREATE TABLE TO C##PROFESOR;
GRANT CREATE TABLE TO C##MARCO;
GRANT CREATE TABLE TO C##ANDRES;

-- Asignar roles a usuarios ---
GRANT C##PRESIDENTE TO C##PROFESOR;
GRANT C##MEDICO TO C##MARCO;
GRANT C##ARBITRO TO C##ANDRES;


