-- Eliminar roles
DROP ROLE C##PRESIDENTE;
DROP ROLE C##MEDICO;
DROP ROLE C##ARBITRO;

DROP PACKAGE PC_ARBITRO;
DROP PACKAGE PC_PRESIDENTE;
DROP PACKAGE PC_MEDICO;

DROP USER C##PROFESOR;
DROP USER C##MARCO;
DROP USER C##ANDRES;