DROP TRIGGER AsignarArbitroEspañol;
DROP TRIGGER trg_control_asistencia_estadio;
DROP TRIGGER trg_evitar_eliminacion_estadio;
DROP TRIGGER trg_actualizar_puntos_equipo;
DROP TRIGGER trg_actualizar_fecha_fundacion_equipo;
DROP TRIGGER trg_control_eliminar_arbitro;