/*Eliminacion de Tablas*/

DROP TABLE Fisica CASCADE CONSTRAINTS;

DROP TABLE Mental CASCADE CONSTRAINTS;

DROP TABLE Evaluacion CASCADE CONSTRAINTS;

DROP TABLE Jugador CASCADE CONSTRAINTS;

DROP TABLE Patrocinadores CASCADE CONSTRAINTS;

DROP TABLE Equipo CASCADE CONSTRAINTS;

DROP TABLE Partido CASCADE CONSTRAINTS;

DROP TABLE Arbitro CASCADE CONSTRAINTS;

DROP TABLE Eventos_Partido CASCADE CONSTRAINTS;

DROP TABLE Estadio CASCADE CONSTRAINTS;

DROP TABLE Medios CASCADE CONSTRAINTS;

DROP TABLE Aficionados CASCADE CONSTRAINTS;

